services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/app:/next-app/app
      - ./next-app/.eslintrc.json:/next-app/.eslintrc.json
      - ./next-app/next.config.mjs:/next-app/next.config.mjs
      - ./next-app/next-env.d.ts:/next-app/next-env.d.ts
      - ./next-app/postcss.config.mjs:/next-app/postcss.config.mjs
      - ./next-app/tailwind.config.ts:/next-app/tailwind.config.ts
      - ./next-app/tsconfig.json:/next-app/tsconfig.json
    restart: always
    ports:
      - 4444:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true